FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

COPY src/ src/
COPY apps/monitor.py monitor.py

CMD ["python3", "monitor.py", "--bot-config", "/config/bot.yaml", "--scraper-config", "/config/scraper.yaml", "--database-config", "/config/database.yaml"]
